### ISSUE TITLE
VST not showing in ableton

### ISSUE THREAD

**Issue by head034** [diracdeltas/vstSpleeter#7] opened 2020-06-06 23:15 UTC
Keep getting this window when i rescan to make the plugin work.
Not sure how to get this to verify in Mac OS catalina..

<img width="467" alt="Screen Shot 2020-06-06 at 6 17 20 PM" src="https://user-images.githubusercontent.com/66537769/83956236-b9a5d580-a829-11ea-81f5-698ff4a783f0.png">

**Comment by mynzcxk** [comment] 2020-06-19 03:20
i dont even get that message - it just doesnt show.

**Comment by diracdeltas** [comment] 2021-10-18 22:12
if you get the unidentified developer message - see https://github.com/diracdeltas/vstSpleeter/issues/4#issuecomment-634195448. closing this as duplicate of #8

**Closed as completed by diracdeltas** 2021-10-18 22:12 UTC
